apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pxcmprs-server.fullname" . }}
  labels:
    {{- include "pxcmprs-server.labels" . | nindent 4 }}
{{- with .Values.settings }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}